language: node_js
node_js: node
script: npm run build
before_deploy: touch ./build/.nojekyll
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  repo: lrc-maker/3.x
  on:
    branch: 3.x
